NEXUS-DNDN/DNDN_Backend

.github/workflows/gradle.yml
appspec.yml
build.gradle
scripts/health.sh
scripts/profile.sh
scripts/start.sh
scripts/stop.sh
scripts/switch.sh
src/main/java/com/dndn/backend/dndn/global/config/ProfileController.java
src/main/java/com/dndn/backend/dndn/global/config/SecurityConfig.java
src/main/resources/application-real1.yml
src/main/resources/application-real2.yml

> #5 
> 개발 편의를 위해 배포 및 CI/CD 구축

Chore: 배포 및 CI/CD 구축

---

scripts/start.sh

Chore[#5]: start.sh 수정

---

src/main/java/com/dndn/backend/dndn/domain/model/controller/TestController.java

Chore: RDS 삭제

---

scripts/profile.sh

> #5 
> profile.sh 파일 수정을 합니다.

Chore: profile.sh 파일 수정

---

scripts/start.sh

Chore: start.sh 수정

---

src/main/resources/application.yml

> #23
> 네이버 redirect-uri 주소 배포 서버로 변경
>

Chore: application.yml 파일 수정

---

.github/workflows/gradle.yml
src/main/java/com/dndn/backend/dndn/domain/user/api/LoginController.java
src/main/java/com/dndn/backend/dndn/domain/user/application/LoginService.java
src/main/java/com/dndn/backend/dndn/domain/user/application/LoginServiceImpl.java
src/main/java/com/dndn/backend/dndn/domain/user/converter/LoginConverter.java
src/main/java/com/dndn/backend/dndn/domain/user/domain/entity/User.java
src/main/java/com/dndn/backend/dndn/domain/user/dto/AuthResponseDTO.java
src/main/java/com/dndn/backend/dndn/global/config/redisconfig/RedisConfig.java
src/main/java/com/dndn/backend/dndn/global/error/code/status/ErrorStatus.java
src/main/java/com/dndn/backend/dndn/global/error/code/status/SuccessStatus.java

> #43
> 자동 로그인, 로그아웃, 회원탈퇴 API 구현
> ❌

[Feat] Implement auto-login, logout, and account deletion APIs

---

src/main/java/com/dndn/backend/dndn/domain/interest/api/InterestController.java
src/main/java/com/dndn/backend/dndn/domain/interest/api/dto/response/InterestInfoResDto.java
src/main/java/com/dndn/backend/dndn/domain/interest/api/dto/response/InterestListResDto.java
src/main/java/com/dndn/backend/dndn/domain/interest/application/InterestService.java
src/main/java/com/dndn/backend/dndn/domain/interest/application/InterestServiceImpl.java
src/main/java/com/dndn/backend/dndn/domain/interest/domain/Interest.java
src/main/java/com/dndn/backend/dndn/domain/interest/domain/repository/InterestRepository.java
src/main/java/com/dndn/backend/dndn/domain/interest/exception/InterestException.java
src/main/java/com/dndn/backend/dndn/domain/user/api/LoginController.java
src/main/java/com/dndn/backend/dndn/domain/user/application/LoginService.java
src/main/java/com/dndn/backend/dndn/domain/user/application/LoginServiceImpl.java
src/main/java/com/dndn/backend/dndn/domain/user/converter/LoginConverter.java
src/main/java/com/dndn/backend/dndn/domain/user/domain/entity/User.java
src/main/java/com/dndn/backend/dndn/domain/user/dto/AuthResponseDTO.java
src/main/java/com/dndn/backend/dndn/global/config/redisconfig/RedisConfig.java
src/main/java/com/dndn/backend/dndn/global/error/code/status/ErrorStatus.java
src/main/java/com/dndn/backend/dndn/global/error/code/status/SuccessStatus.java
src/main/resources/application.yml

> #55 
> 사용자 복지 서비스 관심 기능을 구현합니다.
> 예외 처리는 모든 기능 구현 후 하도록 하겠습니다.

[Feat] 관심 기능 구현

---

src/main/java/com/dndn/backend/dndn/domain/interest/api/InterestController.java
src/main/java/com/dndn/backend/dndn/domain/interest/application/InterestServiceImpl.java
src/main/java/com/dndn/backend/dndn/global/error/code/status/ErrorStatus.java
src/main/java/com/dndn/backend/dndn/global/error/code/status/SuccessStatus.java

[Feat] 예외처리 및 스웨거 문서화

---

src/main/java/com/dndn/backend/dndn/domain/welfare/api/WelfareController.java
src/main/java/com/dndn/backend/dndn/domain/welfare/application/CentralWelfareSyncService.java
src/main/java/com/dndn/backend/dndn/domain/welfare/application/LocalWelfareSyncService.java
src/main/java/com/dndn/backend/dndn/domain/welfare/application/WelfareSyncScheduler.java
src/main/java/com/dndn/backend/dndn/domain/welfareOpenApi/central/dto/response/CentralDetailResDto.java
src/main/java/com/dndn/backend/dndn/domain/welfareOpenApi/local/client/LocalWelfareClient.java

[Feat] 복지 기능 스웨거 설명 추가

---

src/main/java/com/dndn/backend/dndn/global/config/SecurityConfig.java

> ex) #이슈번호, #이슈번호
> CORS 설정 수정

[Chore] CORS 설정 수정

---

src/main/java/com/dndn/backend/dndn/global/config/SecurityConfig.java

[Chore] update cors setting

---

src/main/java/com/dndn/backend/dndn/domain/welfare/application/WelfareSyncScheduler.java

[Chore] welfare data upload

---

src/main/java/com/dndn/backend/dndn/domain/welfare/api/WelfareController.java
src/main/java/com/dndn/backend/dndn/domain/welfare/application/WelfareService.java
src/main/java/com/dndn/backend/dndn/domain/welfare/application/WelfareServiceImpl.java
src/main/java/com/dndn/backend/dndn/domain/welfare/domain/repository/WelfareRepository.java

> #20
> 검색어 + 카테고리로 복지 서비스 목록 조회 기능 구현

[Feat] 검색어 + 카테고리로 복지 서비스 목록 조회 기능 구현

---

src/main/java/com/dndn/backend/dndn/domain/welfare/application/WelfareSyncScheduler.java
src/main/resources/application.yml

Merge main branch into develop

---

src/main/java/com/dndn/backend/dndn/domain/user/api/UserController.java
src/main/java/com/dndn/backend/dndn/domain/user/domain/entity/User.java
src/main/java/com/dndn/backend/dndn/domain/user/service/UserService.java

> #88
> 유저 정보 입력 api 수정, 소셜 로그인을 통해 생성 된 유저 id를 이용하게 변경
> ❌

[Chore] correct user information api logic

---

src/main/java/com/dndn/backend/dndn/domain/user/api/UserController.java
src/main/java/com/dndn/backend/dndn/domain/user/application/DocumentService.java
src/main/java/com/dndn/backend/dndn/domain/user/application/DocumentServiceImpl.java
src/main/java/com/dndn/backend/dndn/domain/user/converter/UserConverter.java
src/main/java/com/dndn/backend/dndn/domain/user/dto/DocumentResponseDTO.java
src/main/java/com/dndn/backend/dndn/domain/welfare/application/WelfareSyncScheduler.java

[Chore] correct download api

---

src/main/java/com/dndn/backend/dndn/domain/application/api/ApplicationController.java
src/main/java/com/dndn/backend/dndn/domain/application/application/ApplicationService.java
src/main/java/com/dndn/backend/dndn/domain/application/application/ApplicationServiceImpl.java
src/main/java/com/dndn/backend/dndn/domain/application/domain/Application.java
src/main/java/com/dndn/backend/dndn/global/error/code/status/ErrorStatus.java
src/main/java/com/dndn/backend/dndn/global/error/code/status/SuccessStatus.java

[Feat] 수령 상태 변경 api 추가

---

src/main/java/com/dndn/backend/dndn/domain/welfare/application/WelfareServiceImpl.java

지역 일치하고 나머지 추가 정보가 하나도 일치하지 않으면 아예 뜨지 않는 버그 발생해 로직 수정함

[Bug] 추천 로직 수정

---

src/main/java/com/dndn/backend/dndn/domain/user/api/LoginController.java
src/main/java/com/dndn/backend/dndn/domain/user/api/WebTestController.java
src/main/java/com/dndn/backend/dndn/domain/user/application/LoginServiceImpl.java
src/main/java/com/dndn/backend/dndn/domain/user/dto/AuthResponseDTO.java

[Chore] correct google login
